print("Welcome to the tip calculator.")
a=input("what was the total bill?")
t=input("what percent tip would u like to give?10,12, or 15")
n=input(" how many people to split the bill")
a=float(a)
n=int(n)
t=int(t)
total=a+a*(t/100)
each=total/n
each=round(each,2)
print(f"Each person should pay:{each}")
